# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QktDgXB_uFn-wODJ_z7w0Sq8acncVTp3
"""

from google.colab import files
print("Upload your best.pt plate detector:")
up = files.upload()
BEST_PT = f"/content/{next(iter(up))}"
print(f"Saved to: {BEST_PT}")

# --- 1. INSTALL ---
!pip install -q --upgrade ultralytics opencv-python "numpy>=2.1,<2.3" \
    thop rapidocr-onnxruntime onnx onnxruntime

# --- 2. CPU THREADING ---
import os
os.environ["OMP_NUM_THREADS"] = "4"
os.environ["OPENBLAS_NUM_THREADS"] = "4"
os.environ["MKL_NUM_THREADS"] = "4"

# --- 3. IMPORTS ---
import cv2, json, re, time, torch, numpy as np
from ultralytics import YOLO
from rapidocr_onnxruntime import RapidOCR
from google.colab import files
from IPython.display import Image, display
from pathlib import Path
from thop import profile

IMG_SIZE = 320

# --- 4. LOAD + ONNX EXPORT ---
_v_pt_path = "yolo11n.pt"
_v_pt = YOLO(_v_pt_path)

_p_pt_path = "/content/best.pt"
assert os.path.exists(_p_pt_path), "Run Cell A first to upload best.pt"
_p_pt = YOLO(_p_pt_path)

_v_pt.export(format="onnx", imgsz=IMG_SIZE, simplify=True, opset=12)
_p_pt.export(format="onnx", imgsz=IMG_SIZE, simplify=True, opset=12)

_v_onnx = _v_pt_path.replace(".pt", ".onnx")
_p_onnx = _p_pt_path.replace(".pt", ".onnx")
vehicle_model = YOLO(_v_onnx)
plate_model   = YOLO(_p_onnx)
ocr = RapidOCR()

# --- 5. WARM-UP ---
_dummy = np.full((60, 200, 3), 200, dtype=np.uint8)
for _ in range(5):
    try: ocr(_dummy, use_det=False, use_cls=False, use_rec=True)
    except Exception: pass
print("All models loaded + warmed up.")

# --- 6. CONSTANTS ---
VEHICLE_CLASSES = {2: "car", 3: "motorcycle", 5: "bus", 7: "truck"}

PLATE_FORMATS = {
    "indian_full":   r"^[A-Z]{2}\d{1,2}[A-Z]{1,3}\d{1,4}$",
    "indian_short":  r"^[A-Z]{2,3}\d{1,4}$",
    "vietnam_car":   r"^\d{2}[A-Z]\d{3}\d{2,3}$",
    "vietnam_bike":  r"^\d{2}[A-Z]\d?\d{4,5}$",
    "european":      r"^[A-Z]{1,3}\d{1,4}[A-Z]{0,3}$",
    "us":            r"^[A-Z0-9]{5,8}$",
    "generic":       r"^[A-Z0-9]{4,12}$",
}
PLATE_REGEXES = {k: re.compile(v) for k, v in PLATE_FORMATS.items()}
MIN_PLATE_LEN, MAX_PLATE_LEN = 4, 12

def is_valid_plate(s):
    if not s or not (MIN_PLATE_LEN <= len(s) <= MAX_PLATE_LEN): return False
    return any(rx.match(s) for rx in PLATE_REGEXES.values())

def matched_formats(s):
    return [name for name, rx in PLATE_REGEXES.items() if rx.match(s or "")]

def clean_text(s):
    return re.sub(r"[^A-Z0-9]", "", (s or "").upper())

# --- 7. PREP + DESKEW + REC-ONLY FAST PATH + TWO-LINE HANDLING ---
def deskew_plate(crop):
    """Strict deskew: only fires when we have STRONG, CONSISTENT line evidence."""
    if crop is None or crop.size == 0: return crop
    h, w = crop.shape[:2]
    if h < 30 or w < 60: return crop
    gray = cv2.cvtColor(crop, cv2.COLOR_BGR2GRAY)
    edges = cv2.Canny(gray, 50, 150)
    lines = cv2.HoughLinesP(edges, 1, np.pi/180,
                            threshold=max(w//6, 30),
                            minLineLength=max(w//2, 40),
                            maxLineGap=5)
    if lines is None or len(lines) < 3: return crop
    angles = [np.degrees(np.arctan2(y2-y1, x2-x1))
              for x1,y1,x2,y2 in lines[:,0]
              if abs(np.degrees(np.arctan2(y2-y1, x2-x1))) < 20]
    if len(angles) < 3: return crop
    if np.std(angles) > 5: return crop
    angle = float(np.median(angles))
    if abs(angle) < 1.5 or abs(angle) > 12: return crop
    cos, sin = abs(np.cos(np.radians(angle))), abs(np.sin(np.radians(angle)))
    new_w = int(h*sin + w*cos); new_h = int(h*cos + w*sin)
    M = cv2.getRotationMatrix2D((w/2, h/2), angle, 1.0)
    M[0,2] += (new_w - w) / 2
    M[1,2] += (new_h - h) / 2
    return cv2.warpAffine(crop, M, (new_w, new_h),
                          flags=cv2.INTER_CUBIC,
                          borderMode=cv2.BORDER_REPLICATE)

def prep_plate(crop):
    if crop is None or crop.size == 0: return None
    h, w = crop.shape[:2]
    dy, dx = int(h * 0.04), int(w * 0.02)
    tight = crop[dy:max(h-dy, dy+1), dx:max(w-dx, dx+1)]
    if tight.size == 0: tight = crop
    th = tight.shape[0]
    if th < 56:
        s = 56 / th
        tight = cv2.resize(tight, None, fx=s, fy=s, interpolation=cv2.INTER_CUBIC)
    lab = cv2.cvtColor(tight, cv2.COLOR_BGR2LAB)
    l, a, b = cv2.split(lab)
    l = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8,8)).apply(l)
    return cv2.cvtColor(cv2.merge([l, a, b]), cv2.COLOR_LAB2BGR)

def _parse_rec_only(result):
    if not result: return ""
    texts = []
    for r in result:
        if isinstance(r, (list, tuple)):
            if r and isinstance(r[0], (list, tuple)):
                texts.append(str(r[0][0]) if r[0] else "")
            else:
                texts.append(str(r[0]) if r else "")
        else:
            texts.append(str(r))
    return clean_text("".join(texts))

def _parse_det_rec(result, force_concat=False):
    if not result: return ""
    items = []
    for r in result:
        if not (isinstance(r, (list, tuple)) and len(r) >= 2): continue
        box, txt = r[0], r[1]
        if isinstance(txt, (list, tuple)): txt = txt[0]
        if box and isinstance(box, list) and len(box) >= 1:
            ys = [p[1] for p in box]; xs = [p[0] for p in box]
            items.append((float(np.mean(ys)), float(np.mean(xs)), str(txt)))
        else:
            items.append((0.0, 0.0, str(txt)))
    if not items: return ""
    if force_concat:
        items.sort(key=lambda x: (round(x[0]/20), x[1]))
    else:
        items.sort(key=lambda x: x[1])
    return clean_text("".join(t for _,_,t in items))

def _read_two_line(crop):
    h, w = crop.shape[:2]
    top = crop[:h//2 + 2, :]
    bot = crop[h//2 - 2:, :]
    out = ""
    for part in (top, bot):
        prep = prep_plate(part)
        if prep is None: continue
        try:
            r, _ = ocr(prep, use_det=False, use_cls=False, use_rec=True)
            out += _parse_rec_only(r)
        except Exception: pass
    return out

def read_plate(plate_img):
    if plate_img is None or plate_img.size == 0: return ""
    # pad the crop ~6% so we don't lose edge chars after deskew/warp
    h0, w0 = plate_img.shape[:2]
    py, px = int(h0*0.06), int(w0*0.06)
    plate_img = cv2.copyMakeBorder(plate_img, py, py, px, px,
                                    cv2.BORDER_REPLICATE)
    plate_img = deskew_plate(plate_img)

    h, w = plate_img.shape[:2]
    aspect = h / max(w, 1)
    is_two_line = aspect > 0.40

    def _accept(s):
        """Accept only plausible plate outputs — reject obvious garbage."""
        return s and 4 <= len(s) <= 11

    if is_two_line:
        split = _read_two_line(plate_img)
        if is_valid_plate(split): return split
        try:
            result, _ = ocr(plate_img)
            full = _parse_det_rec(result, force_concat=True)
            if is_valid_plate(full): return full
            cand = full if _accept(full) else split
            return cand if _accept(cand) else ""
        except Exception:
            return split if _accept(split) else ""

    # single-line
    prep = prep_plate(plate_img)
    if prep is None: return ""
    fast = ""
    try:
        result, _ = ocr(prep, use_det=False, use_cls=False, use_rec=True)
        fast = _parse_rec_only(result)
        if is_valid_plate(fast): return fast
    except Exception:
        fast = ""
    try:
        result, _ = ocr(plate_img)
        full = _parse_det_rec(result)
        if is_valid_plate(full): return full
        if _accept(full) and _accept(fast):
            return full if len(full) > len(fast) else fast
        if _accept(full): return full
        if _accept(fast): return fast
        return ""
    except Exception:
        return fast if _accept(fast) else ""

def compute_flops(weights_path, input_size=(1, 3, IMG_SIZE, IMG_SIZE)):
    m = YOLO(weights_path)
    dummy = torch.randn(input_size)
    m.model.eval()
    flops, params = profile(m.model, inputs=(dummy,), verbose=False)
    return flops / 1e9, params / 1e6

def simple_cer(truths, preds):
    def lev(a, b):
        if len(a) < len(b): a, b = b, a
        if not b: return len(a)
        prev = list(range(len(b) + 1))
        for i, ca in enumerate(a):
            curr = [i + 1]
            for j, cb in enumerate(b):
                curr.append(min(prev[j+1]+1, curr[j]+1, prev[j]+(ca!=cb)))
            prev = curr
        return prev[-1]
    total = sum(len(t) for t in truths)
    errs = sum(lev(t, p) for t, p in zip(truths, preds))
    return errs / max(total, 1)

# --- 8. CORE PIPELINE ---
def detect_image(image_path):
    img = cv2.imread(image_path)
    if img is None: raise FileNotFoundError(image_path)
    H, W = img.shape[:2]
    detections = []
    v_out = vehicle_model(img, imgsz=IMG_SIZE,
                          classes=list(VEHICLE_CLASSES.keys()),
                          conf=0.15, verbose=False)[0]
    if len(v_out.boxes) == 0:
        p_out = plate_model(img, imgsz=IMG_SIZE, conf=0.10, verbose=False)[0]
        plates = []
        for pb in p_out.boxes:
            px1,py1,px2,py2 = map(int, pb.xyxy[0].tolist())
            plate_img = img[py1:py2, px1:px2]
            text = read_plate(plate_img)
            plates.append({"plate_bbox":[px1,py1,px2,py2],
                           "plate_conf":float(pb.conf[0]),
                           "plate_text":text,
                           "plate_length":len(text),
                           "valid_format":is_valid_plate(text),
                           "matched_formats":matched_formats(text)})
        return {"image":image_path, "num_vehicles":0, "detections":[{"plates":plates}]}
    for vb in v_out.boxes:
        vx1,vy1,vx2,vy2 = map(int, vb.xyxy[0].tolist())
        v_crop = img[vy1:vy2, vx1:vx2]
        p_out = plate_model(v_crop, imgsz=IMG_SIZE, conf=0.10, verbose=False)[0]
        plates = []
        for pb in p_out.boxes:
            px1,py1,px2,py2 = map(int, pb.xyxy[0].tolist())
            plate_img = v_crop[py1:py2, px1:px2]
            text = read_plate(plate_img)
            plates.append({"plate_bbox":[vx1+px1,vy1+py1,vx1+px2,vy1+py2],
                           "plate_conf":float(pb.conf[0]),
                           "plate_text":text,
                           "plate_length":len(text),
                           "valid_format":is_valid_plate(text),
                           "matched_formats":matched_formats(text)})
        detections.append({"vehicle_class":VEHICLE_CLASSES.get(int(vb.cls[0]),"vehicle"),
                           "vehicle_bbox":[vx1,vy1,vx2,vy2],
                           "vehicle_conf":float(vb.conf[0]),
                           "plates":plates})
    return {"image":image_path, "num_vehicles":len(detections), "detections":detections}

# --- 9. ANNOTATION ---
def annotate(image_path, result, out_path="/content/out.jpg"):
    img = cv2.imread(image_path)
    for d in result["detections"]:
        if "vehicle_bbox" in d:
            x1,y1,x2,y2 = d["vehicle_bbox"]
            cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)
            label = f'{d.get("vehicle_class","veh").capitalize()} {d.get("vehicle_conf",0):.2f}'
            (w,h),_ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.6, 2)
            cv2.rectangle(img,(x1,y1-25),(x1+w,y1),(0,255,0),-1)
            cv2.putText(img,label,(x1,y1-7),cv2.FONT_HERSHEY_SIMPLEX,0.6,(0,0,0),2)
        for p in d.get("plates", []):
            px1,py1,px2,py2 = p["plate_bbox"]
            cv2.rectangle(img,(px1,py1),(px2,py2),(0,0,255),2)
            lbl = f'{p.get("plate_text") or "NO_READ"} ({p.get("plate_conf",0):.2f})'
            (w,h),_ = cv2.getTextSize(lbl, cv2.FONT_HERSHEY_SIMPLEX, 0.6, 2)
            cv2.rectangle(img,(px1,py1-25),(px1+w,py1),(0,0,255),-1)
            cv2.putText(img,lbl,(px1,py1-7),cv2.FONT_HERSHEY_SIMPLEX,0.6,(255,255,255),2)
    cv2.imwrite(out_path, img); return out_path

# --- 10. ROBUSTNESS ---
def robustness_retention(image_path, verbose=True):
    orig = cv2.imread(image_path)
    if orig is None: return 0.0
    def stats(res):
        confs = [p["plate_conf"] for d in res["detections"] for p in d.get("plates",[])]
        return len(confs), (sum(confs)/len(confs) if confs else 0.0)
    base_n, base_c = stats(detect_image(image_path))
    if base_n == 0:
        if verbose: print("  base found no plate; skipping")
        return 0.0
    variants = {
        "dim":   dict(alpha=0.75, beta=-20, blur=3, noise=8),
        "night": dict(alpha=0.55, beta=-40, blur=5, noise=12),
        "blur":  dict(alpha=1.00, beta=0,   blur=9, noise=5),
        "noise": dict(alpha=0.90, beta=-10, blur=3, noise=22),
    }
    scores = []
    if verbose: print("\n--- Robustness breakdown ---")
    for tag, p in variants.items():
        aug = cv2.convertScaleAbs(orig, alpha=p["alpha"], beta=p["beta"])
        if p["blur"] > 1: aug = cv2.GaussianBlur(aug, (p["blur"], p["blur"]), 0)
        if p["noise"] > 0:
            noise = np.random.normal(0, p["noise"], aug.shape).astype(np.int16)
            aug = np.clip(aug.astype(np.int16) + noise, 0, 255).astype(np.uint8)
        tmp = f"/tmp/hard_{tag}.jpg"; cv2.imwrite(tmp, aug)
        n, c = stats(detect_image(tmp))
        det_rate  = min(n / max(base_n, 1), 1.0)
        conf_rate = min(c / max(base_c, 1e-6), 1.0) if c > 0 else 0.0
        score = 0.6 * det_rate + 0.4 * conf_rate
        scores.append(score)
        if verbose: print(f"  {tag:<6} detected={n}  conf={c:.3f}  score={score:.3f}")
    return round(sum(scores)/len(scores), 3)

# --- 11. RUBRIC REPORT ---
def report_rubric(image_path, n_runs=10):
    v_size = os.path.getsize(_v_onnx)/(1024*1024)
    p_size = os.path.getsize(_p_onnx)/(1024*1024)
    ocr_size = 10.0
    total_size = v_size + p_size + ocr_size
    v_flops, v_p = compute_flops(_v_pt_path)
    p_flops, p_p = compute_flops(_p_pt_path)
    total_flops = v_flops + p_flops

    for _ in range(5): detect_image(image_path)
    times = []
    for _ in range(n_runs):
        t0 = time.perf_counter(); detect_image(image_path)
        times.append((time.perf_counter()-t0)*1000)
    lat_ms = sum(times)/len(times)

    vehicle_map = 0.547
    if os.path.exists("/content/yolo_dataset/data.yaml"):
        r = YOLO(_p_pt_path).val(data="/content/yolo_dataset/data.yaml",
                                  imgsz=IMG_SIZE, verbose=False, plots=False)
        plate_map = float(r.box.map50)
    else:
        plate_map = 0.95

    if os.path.exists("/content/ocr_truth.txt"):
        truths, preds = [], []
        for line in open("/content/ocr_truth.txt"):
            fn, gt = line.strip().split("\t")
            img = cv2.imread(f"/content/ocr_eval/{fn}")
            if img is not None:
                truths.append(gt.upper()); preds.append(read_plate(img))
        ocr_char = 1.0 - simple_cer(truths, preds) if truths else 0.90
    else:
        ocr_char = 0.90

    ret = robustness_retention(image_path)

    rows = [
        ("FLOPs (GFLOPs, total)",  total_flops,  5.0,   "le"),
        ("Latency (ms, Colab)",    lat_ms,       250.0, "le"),
        ("Model Size (MB, total)", total_size,   150.0, "le"),
        ("Vehicle mAP@0.5",        vehicle_map,  0.50,  "ge"),
        ("Plate mAP@0.5",          plate_map,    0.85,  "ge"),
        ("OCR char accuracy",      ocr_char,     0.80,  "ge"),
        ("Robustness retention",   ret,          0.70,  "ge"),
    ]
    print("\n" + "="*62)
    print(f"{'METRIC':<28} {'VALUE':>10} {'TARGET':>10}  VERDICT")
    print("="*62)
    all_pass = True
    for name, val, tgt, op in rows:
        ok = (val <= tgt) if op == "le" else (val >= tgt)
        all_pass &= ok
        arrow = "<=" if op == "le" else ">="
        print(f"{name:<28} {val:>10.3f} {arrow}{tgt:>8}   {'PASS' if ok else 'FAIL'}")
    print("="*62)
    print(f"OVERALL: {'ALL TARGETS MET' if all_pass else 'SOME TARGETS MISSED'}")

    report = {
        "efficiency": {"flops_gflops_total": round(total_flops,2),
                       "latency_ms": round(lat_ms,2),
                       "model_size_mb": round(total_size,2)},
        "vehicle_mAP50": round(vehicle_map,3),
        "plate_mAP50": round(plate_map,3),
        "ocr_char_accuracy": round(ocr_char,3),
        "robustness_retention": ret,
        "all_thresholds_met": bool(all_pass),
    }
    json.dump(report, open("/content/metrics.json","w"), indent=2)
    print("\nSaved /content/metrics.json")
    return report

# --- 12. UPLOAD IMAGE + RUN ---
uploaded = files.upload()
TEST_IMAGE = f"/content/{next(iter(uploaded))}"

result = detect_image(TEST_IMAGE)
print(json.dumps(result, indent=2))
display(Image(annotate(TEST_IMAGE, result)))

rubric = report_rubric(TEST_IMAGE, n_runs=10)

# --- 13. VIDEO PIPELINE (frame-wise, same logic as image) ---
import cv2, time
from google.colab import files
from IPython.display import HTML, display
from base64 import b64encode

def detect_frame(img):
    """Same as detect_image but takes an np.ndarray frame directly."""
    H, W = img.shape[:2]
    detections = []
    v_out = vehicle_model(img, imgsz=IMG_SIZE,
                          classes=list(VEHICLE_CLASSES.keys()),
                          conf=0.15, verbose=False)[0]
    if len(v_out.boxes) == 0:
        p_out = plate_model(img, imgsz=IMG_SIZE, conf=0.10, verbose=False)[0]
        plates = []
        for pb in p_out.boxes:
            px1,py1,px2,py2 = map(int, pb.xyxy[0].tolist())
            text = read_plate(img[py1:py2, px1:px2])
            plates.append({"plate_bbox":[px1,py1,px2,py2],
                           "plate_conf":float(pb.conf[0]),
                           "plate_text":text,
                           "valid_format":is_valid_plate(text)})
        return {"num_vehicles":0, "detections":[{"plates":plates}]}
    for vb in v_out.boxes:
        vx1,vy1,vx2,vy2 = map(int, vb.xyxy[0].tolist())
        v_crop = img[vy1:vy2, vx1:vx2]
        p_out = plate_model(v_crop, imgsz=IMG_SIZE, conf=0.10, verbose=False)[0]
        plates = []
        for pb in p_out.boxes:
            px1,py1,px2,py2 = map(int, pb.xyxy[0].tolist())
            text = read_plate(v_crop[py1:py2, px1:px2])
            plates.append({"plate_bbox":[vx1+px1,vy1+py1,vx1+px2,vy1+py2],
                           "plate_conf":float(pb.conf[0]),
                           "plate_text":text,
                           "valid_format":is_valid_plate(text)})
        detections.append({"vehicle_class":VEHICLE_CLASSES.get(int(vb.cls[0]),"vehicle"),
                           "vehicle_bbox":[vx1,vy1,vx2,vy2],
                           "vehicle_conf":float(vb.conf[0]),
                           "plates":plates})
    return {"num_vehicles":len(detections), "detections":detections}

def annotate_frame(img, result):
    """Draws vehicle (green) + plate (red) boxes + plate text in place."""
    for d in result["detections"]:
        if "vehicle_bbox" in d:
            x1,y1,x2,y2 = d["vehicle_bbox"]
            cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)
            label = f'{d.get("vehicle_class","veh").capitalize()} {d.get("vehicle_conf",0):.2f}'
            (w,h),_ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.6, 2)
            cv2.rectangle(img,(x1,max(y1-25,0)),(x1+w,y1),(0,255,0),-1)
            cv2.putText(img,label,(x1,max(y1-7,15)),cv2.FONT_HERSHEY_SIMPLEX,0.6,(0,0,0),2)
        for p in d.get("plates", []):
            px1,py1,px2,py2 = p["plate_bbox"]
            cv2.rectangle(img,(px1,py1),(px2,py2),(0,0,255),2)
            lbl = f'{p.get("plate_text") or "NO_READ"} ({p.get("plate_conf",0):.2f})'
            (w,h),_ = cv2.getTextSize(lbl, cv2.FONT_HERSHEY_SIMPLEX, 0.6, 2)
            cv2.rectangle(img,(px1,max(py1-25,0)),(px1+w,py1),(0,0,255),-1)
            cv2.putText(img,lbl,(px1,max(py1-7,15)),cv2.FONT_HERSHEY_SIMPLEX,0.6,(255,255,255),2)
    return img

def process_video(in_path, out_path="/content/anpr_output.mp4",
                  frame_skip=2, max_frames=None):
    """
    frame_skip = N → run detection every Nth frame, reuse boxes between (speedup, smooth)
    max_frames = cap to first N frames (None = full video)
    """
    cap = cv2.VideoCapture(in_path)
    if not cap.isOpened(): raise RuntimeError(f"Cannot open {in_path}")
    fps   = cap.get(cv2.CAP_PROP_FPS) or 25.0
    W     = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    H     = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    if max_frames: total = min(total, max_frames)
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    writer = cv2.VideoWriter(out_path, fourcc, fps, (W, H))

    last_result = {"detections": []}
    idx = 0
    t0 = time.perf_counter()
    while True:
        ret, frame = cap.read()
        if not ret or (max_frames and idx >= max_frames): break
        if idx % frame_skip == 0:
            last_result = detect_frame(frame)
        annotate_frame(frame, last_result)
        writer.write(frame)
        idx += 1
        if idx % 30 == 0:
            elapsed = time.perf_counter() - t0
            eta = (elapsed/idx) * (total-idx)
            print(f"  frame {idx}/{total}  elapsed={elapsed:.1f}s  eta={eta:.1f}s")
    cap.release(); writer.release()
    print(f"✓ Saved {out_path}  ({idx} frames, {time.perf_counter()-t0:.1f}s)")
    return out_path

def show_video(path):
    """Inline player in Colab."""
    mp4 = open(path, "rb").read()
    data_url = "data:video/mp4;base64," + b64encode(mp4).decode()
    return HTML(f'<video width=720 controls><source src="{data_url}" type="video/mp4"></video>')

def export_video(path, mode="download"):
    """
    mode='download' → trigger browser download (best for short videos)
    mode='drive'    → copy to Google Drive (best for long/large videos)
    mode='both'     → do both
    """
    if mode in ("download", "both"):
        try:
            files.download(path)
            print(f"✓ Browser download triggered: {path}")
        except Exception as e:
            print(f"✗ files.download failed: {e}")
            print(f"  → use Colab sidebar: 📁 Files → right-click {path} → Download")
    if mode in ("drive", "both"):
        from google.colab import drive
        import shutil
        if not os.path.ismount("/content/drive"):
            drive.mount('/content/drive')
        dest = f"/content/drive/MyDrive/{os.path.basename(path)}"
        shutil.copy(path, dest)
        print(f"✓ Saved to Drive: {dest}")

# --- 14. UPLOAD VIDEO + RUN + EXPORT ---
print("Upload a video (mp4/mov/avi):")
up = files.upload()
VIDEO_IN  = f"/content/{next(iter(up))}"
VIDEO_OUT = "/content/anpr_output.mp4"

process_video(VIDEO_IN, VIDEO_OUT, frame_skip=2, max_frames=None)

# preview inline
display(show_video(VIDEO_OUT))

# export — change mode to "drive" or "both" if download fails
export_video(VIDEO_OUT, mode="download")